version: '3.9'

services:
  backend:
    container_name: backend
    build: .
    ports:
      - '3001:3001'
    volumes:
      - .:/app
    env_file: .env
    # stdin_open: true
    # tty: true
    depends_on:
      - mongodb
      - mongo-express

  mongodb:
    image: mongo:5.0
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin@mongodb:27017/
    depends_on:
      - mongodb
